<?php
$posts = $this->getPostCollection();
?>
<?php if(count($posts) > 0): ?>

<?php
$descLength = $this->getDescLength();
$useSlider = $this->getUseSlider();
$itemClass = $useSlider?'col-sm-24':'col-sm-8';
$width = $this->getThumbWidth();
$height = $this->getThumbHeight();
$helper = Mage::helper('blogfeatures');
$size = array('width' => $width,'height' => $height);
$dateHelper = Mage::getModel('core/date');
$uniqId = uniqid();
$placeholder = $helper->getPlaceholderUrl($size);
?>
<div class="cdz_wapper-blog02" id="<?php echo 'post-'.$uniqId ?>">
    <div class="cdz-block-title">
	    <p class="h2"><span><?php echo $this->getBlogTitle() ?></span></p>
    </div>
    <div class="cdz_wapper-blog-content">
    <div class="post-items <?php echo $useSlider?'cdz-post-slider':''; ?>">
    	<?php foreach($posts as $item): ?>
        <?php
			$url = $this->getUrl("blog/{$item->getIdentifier()}");
			$title = $this->stripTags($item->getTitle());
		?>
        <div class="cdz-post">            
            <div class="cdz-blog-top">
            	<?php if($this->show('created_time')): ?>
                <?php $date = $dateHelper->date('D m, Y',$item->getCreatedTime()); ?>
                <div class="blog-date"><?php echo $date ?></div>
                <?php endif ?>
            	<?php if($this->show('title')): ?>
            	<h5 class="blog-title"><a title="<?php echo $title ?>" href="<?php echo $url ?>"><?php echo $title ?></a></h5>
                <?php endif ?>
                
                <?php if($this->show('user')): ?>
                <div class="blog-author"><?php echo $this->__('Post by').' '.$item->getUser() ?></div>
                <?php endif ?>
                
                <?php if($this->show('short_content')): ?>
                <?php
					$desc = $item->getShortContent();
					if(strlen($desc)> $descLength ) { 
						$strCutDesc = substr($desc, 0, $descLength);
						$desc = substr($strCutDesc, 0, strrpos($strCutDesc, ' ')).'&hellip;';
					}
					$desc = $this->stripTags($desc,null,true);
				?>
                <div class="blog-desc"><?php echo $desc ?></div>
                <?php endif ?>
            </div>
            <div class="cdz-blog-bottom">
            	<?php if($this->show('post_image')): ?>
            	<a href="<?php echo $url ?>">
                	<img class="img-responsive cdz-lazy" src="<?php echo $placeholder ?>" alt="<?php echo $item->getTitle() ?>" data-src="<?php echo $helper->getImage($item,$size) ?>" />
                </a>
                <?php endif ?>
            </div>
        </div>
        <?php endforeach ?>
    </div>
    </div>
</div>
<?php if($useSlider): ?>
<script>
	(function( $ ) {
		$(document).ready(function(e) {
			var $wrapper = $('#<?php echo 'post-'.$uniqId ?>');
			var $owl = $wrapper.find('.cdz-post-slider');
			$owl.addClass('owl-carousel owl-theme');
			$owl.owlCarousel({
				loop: false,
				margin: 20,
				responsiveClass: true,
				nav: true,
				dots: false,
				responsive:{
					0:{items: 	<?php echo $this->getItems_0() ?>},
					320:{items:	<?php echo $this->getItems_320() ?>},
					480:{items:	<?php echo $this->getItems_480() ?>},
					768:{items: <?php echo $this->getItems_768() ?>},
					1024:{items: <?php echo $this->getItems_1024() ?>},
					1280:{items: <?php echo $this->getItems_1280() ?>}	
				}
			});
			var makeSameHeight = function(){
				$wrapper.sameHeightItems({
					parent: '.post-items',
					sItem: '.cdz-blog-top'
				});
				$wrapper.sameHeightItems({
					parent: '.post-items',
					sItem: '.blog-title'
				});
			};
			makeSameHeight();
			$(window).resize(function(){setTimeout(makeSameHeight,500)});
        });
	})( jQuery );
</script>
<?php endif ?>
<?php else: ?>


<?php endif ?>