<?php if( $this->canShowIframe() ): ?>
<div class="qs-modal modal" id="cdz-qsiframe" tabindex="-1" role="dialog" style="display:none;">
	<div class="ajax-load-wrapper" style="display: none;">
        <div class="ajax-load-button">
            <div class="ajax-loader">Loading...</div>
        </div>
    </div>
    <div class="modal-dialog modal-lg animated zoomIn" role="document" style="display:none;"></div>
</div>
<?php endif ?>