<?php
$pageUrl = $this->getPageUrl();
$hideCover = (bool)$this->getHideCover();
$showFacepile = (bool)$this->getShowFacepile();
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=525188320996791";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-page" 
	data-href="<?php echo $pageUrl ?>" 	
	data-small-header="false"
	data-adapt-container-width="true"
	data-hide-cover="<?php echo $hideCover?'true':'false' ?>"
	data-show-facepile="<?php echo $showFacepile?'true':'false' ?>">
	<div class="fb-xfbml-parse-ignore">
		<blockquote cite="<?php echo $pageUrl ?>">
			<a href="<?php echo $pageUrl ?>">Facebook</a>
		</blockquote>
	</div>
</div>
