<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.16
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>

<?php $posts = $this->getPosts();
$posts->getSelect()->group('main_table.post_id');?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<?php
$helper = Mage::helper('blogfeatures');
$width = 380;
$height = 280;
?>

<!-- <div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
 -->
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<ol class="post-list">
<?php foreach ($posts as $_post): ?>
    <li class="row postWrapper postWrapper-<?php echo $_post->getId() ?>">
		<div class="post-image cdz-blog-left col-sm-10">
		    <a href="<?php echo $_post->getAddress() ?>">                
		         <img class="img-responsive" width="<?php echo $width ?>" height="<?php echo $height ?>" src="<?php echo $helper->getImage($_post,array('width' => $width,'height' => $height)) ?>" />
		    </a>
		    <div class="blog-date"><?php echo $_post->getCreatedTime(); ?></span></div>
		</div>
		<div class="post-details cdz-blog-right col-sm-14">
		    <div class="post-header">

		        <div class="postTitle clearfix">
					<div class="postTitle-blog">
		            <h2 class="post-title">
		                <a class="post-item-link"
		                   href="<?php echo $_post->getAddress() ?>">
		                    <?php echo $_post->getTitle(); ?>
		                </a>
		            </h2>
					</div>
		            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_post->getAddress() ?>">
		                <a class="addthis_button_facebook"></a>
		                <a class="addthis_button_twitter"></a>
		                <a class="addthis_button_email"></a>
		                <a class="addthis_button_compact"></a>
		            </div>
		        </div>

		        <?php echo $this->getInfoHtml() ?>
		    </div>

		    <div class="postContent">
		        <div class="post-description clearfix">
		            <?php
		            		$descLength = 250;
					$desc = $_post->getPostContent();
					if(strlen($desc)> $descLength ) { 
						$strCutDesc = substr($desc, 0, $descLength);
						$desc = substr($strCutDesc, 0, strrpos($strCutDesc, ' ')).'&hellip;';
					}
					$desc = $this->stripTags($desc,null,true);
				?>
				<?php echo $desc; ?>
		            
		        </div>
				<a class="aw-blog-read-more" href="<?php echo $_post->getAddress() ?>" title="<?php echo $_post->getTitle() ?>"
				   >
				   <?php echo __('Continue Read') ?>
				</a>
		    </div>
		</div>
		<div class="post-footer">

		</div>
	</li>
<?php endforeach; ?>
</ol>
<script type="text/javascript">var addthis_config = {"data_track_clickback":false};</script>
<script type="text/javascript" async src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4def63cd3cf37569"></script>
<script type="text/javascript">
    var addthis_config = {
        ui_language: "en"
    }
</script>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
