<?php
    $_item = $this->getItem();
    $isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
    $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
	$formId = 'updatecart_form_'.$_item->getId();
?>
<li class="cart-item" >
	<div class="product">
		<strong><?php echo $this->getQty() ?></strong>
		<span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(78, 78)->setWatermarkSize('30x10'); ?>" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></span>
    </div>
    <div class="product-details">
		<div class="product-hover-container">
			<div class="product-hover-inner">
            	<?php if($_item->getProduct()->getTypeId() == 'simple'): ?>          	
            	<form class="ajax-update-cart" id="<?php echo $formId ?>" action="<?php echo $this->getUrl('checkout/cart/updateItemOptions',array('id' => $_item->getId())) ?>" method="post">
					<input class="item-qty cart-item-qty" name="qty" value="<?php echo $this->getQty() ?>">
                   
					
                        
                        <?php if ($isVisibleProduct): ?>
                        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('OK')) ?>" class="btn-edit"><?php echo $this->__('OK')?></button>
						<a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>" onclick="return confirm('<?php echo Mage::helper('core')->quoteEscape($this->__('Are you sure you would like to remove this item from the shopping cart?'), true) ?>');" class="btn-remove"><?php echo $this->__('Remove Item') ?></a>
                    
                    <?php endif ?>
                </form>
                <?php else: ?>
                	<input class="item-qty cart-item-qty" name="qty" value="<?php echo $this->getQty() ?>">
                	
                       
                        <?php if ($isVisibleProduct): ?>
                        <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('OK')) ?>" class="btn-edit"><?php echo $this->__('OK')?></a>
                        <?php endif ?>
						 <a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>" onclick="return confirm('<?php echo Mage::helper('core')->quoteEscape($this->__('Are you sure you would like to remove this item from the shopping cart?'), true) ?>');" class="btn-remove"><?php echo $this->__('Remove Item') ?></a>
				
                <?php endif ?>
			</div>
		</div>
    </div>
</li>
