<?php
    $_product = $this->getProduct();
	$_product->load('media_gallery');
    $_helper = $this->helper('catalog/output');
	$_imgHelper = $this->helper('catalog/image');
	$_gallery = $this->getGalleryImages();
?>
<?php if (count($_gallery) > 0): ?>
<div class="cdz-media-wrap">
<ul class="cdz-media media-slider">
<?php foreach ($_gallery as $_image): ?>
	<?php $_smallImg = $_imgHelper->init($_product, 'thumbnail', $_image->getFile())->resize(80,80); ?>
	<li class="img-item">
    	<img src="<?php echo $_smallImg ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
    </li>
<?php endforeach ?>
</ul>
</div>
<?php endif ?>