<?php
class Codazon_Slideshow_Model_Listeffect extends Varien_Object
{
    public function toOptionArray()
    {
        return array(           
            'bounce'=> Mage::helper('slideshow')->__('bounce') ,
            'flash'=> Mage::helper('slideshow')->__('flash') ,
            'pulse'=> Mage::helper('slideshow')->__('pulse') ,
            'rubberBand'=> Mage::helper('slideshow')->__('rubberBand') ,          
            'shake'=> Mage::helper('slideshow')->__('shake') ,
            'swing'=> Mage::helper('slideshow')->__('swing') ,
            'tada'=> Mage::helper('slideshow')->__('tada') ,
            'wobble'=> Mage::helper('slideshow')->__('wobble') ,
            'bounceIn'=> Mage::helper('slideshow')->__('bounceIn') ,
            'bounceInDown'=> Mage::helper('slideshow')->__('bounceInDown') ,
            'bounceInLeft'=> Mage::helper('slideshow')->__('bounceInLeft') ,
            'bounceInRight'=> Mage::helper('slideshow')->__('bounceInRight') ,          
            'bounceInUp'=> Mage::helper('slideshow')->__('bounceInUp') ,
            'bounceOut'=> Mage::helper('slideshow')->__('bounceOut') ,
            'bounceOutDown'=> Mage::helper('slideshow')->__('bounceOutDown') ,
            'bounceOutLeft'=> Mage::helper('slideshow')->__('bounceOutLeft') ,
            'bounceOutRight'=> Mage::helper('slideshow')->__('bounceOutRight') ,          
            'bounceOutUp'=> Mage::helper('slideshow')->__('bounceOutUp') ,
            'fadeIn'=> Mage::helper('slideshow')->__('fadeIn') ,
            'fadeInDown'=> Mage::helper('slideshow')->__('fadeInDown') ,
            'fadeInDownBig'=> Mage::helper('slideshow')->__('fadeInDownBig') ,
            'fadeInLeft'=> Mage::helper('slideshow')->__('fadeInLeft') ,          
            'fadeInLeftBig'=> Mage::helper('slideshow')->__('fadeInLeftBig') ,
            'fadeInRight'=> Mage::helper('slideshow')->__('fadeInRight') ,
            'fadeInRightBig'=> Mage::helper('slideshow')->__('fadeInRightBig') ,
            'fadeInUp'=> Mage::helper('slideshow')->__('fadeInUp') ,
            'fadeInUpBig'=> Mage::helper('slideshow')->__('fadeInUpBig') ,
            'fadeOut'=> Mage::helper('slideshow')->__('fadeOut') ,
            'fadeOutDown'=> Mage::helper('slideshow')->__('fadeOutDown') ,
            'fadeOutDownBig'=> Mage::helper('slideshow')->__('fadeOutDownBig') ,
            'fadeOutLeft'=> Mage::helper('slideshow')->__('fadeOutLeft') ,          
            'fadeOutLeftBig'=> Mage::helper('slideshow')->__('fadeOutLeftBig') ,
            'fadeOutRight'=> Mage::helper('slideshow')->__('fadeOutRight') ,
            'fadeOutRightBig'=> Mage::helper('slideshow')->__('fadeOutRightBig') ,
            'fadeOutUp'=> Mage::helper('slideshow')->__('fadeOutUp') ,
            'fadeOutUpBig'=> Mage::helper('slideshow')->__('fadeOutUpBig') ,
            'flip'=> Mage::helper('slideshow')->__('flip') ,
            'flipInX'=> Mage::helper('slideshow')->__('flipInX') ,
            'flipInY'=> Mage::helper('slideshow')->__('flipInY') ,
            'flipOutX'=> Mage::helper('slideshow')->__('flipOutX') ,          
            'flipOutY'=> Mage::helper('slideshow')->__('flipOutY') ,
            'lightSpeedIn'=> Mage::helper('slideshow')->__('lightSpeedIn') ,
            'lightSpeedOut'=> Mage::helper('slideshow')->__('lightSpeedOut') ,
            'rotateIn'=> Mage::helper('slideshow')->__('rotateIn') ,
            'rotateInDownLeft'=> Mage::helper('slideshow')->__('rotateInDownLeft') ,
            'rotateInDownRight'=> Mage::helper('slideshow')->__('rotateInDownRight') ,
            'rotateInUpLeft'=> Mage::helper('slideshow')->__('rotateInUpLeft') ,          
            'rotateInUpRight'=> Mage::helper('slideshow')->__('rotateInUpRight') ,
            'rotateOut'=> Mage::helper('slideshow')->__('rotateOut') ,
            'rotateOutDownLeft'=> Mage::helper('slideshow')->__('rotateOutDownLeft') ,
            'rotateOutDownRight'=> Mage::helper('slideshow')->__('rotateOutDownRight') ,
            'rotateOutUpLeft'=> Mage::helper('slideshow')->__('rotateOutUpLeft') ,          
            'rotateOutUpRight'=> Mage::helper('slideshow')->__('rotateOutUpRight') ,
            'slideInDown'=> Mage::helper('slideshow')->__('slideInDown') ,
            'slideInLeft'=> Mage::helper('slideshow')->__('slideInLeft') ,
            'slideInRight'=> Mage::helper('slideshow')->__('slideInRight') ,
            'slideOutLeft'=> Mage::helper('slideshow')->__('slideOutLeft') ,          
            'slideOutRight'=> Mage::helper('slideshow')->__('slideOutRight') ,
            'slideOutUp'=> Mage::helper('slideshow')->__('slideOutUp') ,
            'hinge'=> Mage::helper('slideshow')->__('hinge') ,
            'rollIn'=> Mage::helper('slideshow')->__('rollIn') ,
            'rollOut'=> Mage::helper('slideshow')->__('rollOut') ,
        );
    }
}